apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: sharing key
spec:
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
  selector:
    app: wordpress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      restartPolicy: Always
      containers:
      - image: mywordpress
        name: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        env:
          - name: DB_NAME
            value: wordpress
          - name: DB_USER
            value: alesanto
          - name: DB_PASSWORD
            value: admin
          - name: DB_HOST
            value: mysql
